### ISSUE TITLE
Proposal to propagated back to the caller an error returned by the invoked function

### ISSUE THREAD

**Issue by dmvass** [NVIDIA/gontainer#30]
**What:** propagated back to the caller an error returned by the invoked function `doSomething`

```go
func doSomething() error {
    ...
    return errDo
}

...

if _, err := container.Invoke(doSomething); err != nil {
    if errors.Is(err , errDo) { 
        // handle doSomething error
    }
    // handle container errors
}
```

Invoked function result `[]any` may be empty in this way.

**Why:** 
1. It's not very convenient to inspect and assert invoked function result `[]any` just to check an error.
2. The current documentation is not clear, and I expected a such behavior before looked to the source. So I guess that other developers may have the same opinion.
3. It's similar to other dependency injection packages like Uber's [dig](https://pkg.go.dev/go.uber.org/dig#hdr-Invoke).

**Comment by pavelpatrin** [comment]
Alternatively it is possible to wrap function results with the interface wrapper like this:

```
type InvokeResult interface {
	Values() []any
	Error() error
}
```

* This will simplify access to the function error, if any.
* This will not panic on a call if function has no error return value.
* As a bonus we are ready to add parametrized getters to this interface if https://github.com/golang/go/issues/49085 will be solved.

**Comment by pavelpatrin** [comment]
https://github.com/NVIDIA/gontainer/pull/31/files

**Comment by pavelpatrin** [comment]
Thank you for you proposal. Done.

**Comment by dmvass** [comment]
@pavelpatrin thanks for released changes! Sorry for late reply, I was on a vacation.
